-- MySQL Script generated by MySQL Workbench
-- Sat Feb 18 20:00:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helpdesk` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `helpdesk` ;

-- -----------------------------------------------------
-- Table `helpdesk`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`departamentos` (
  `id_departamento` INT NOT NULL AUTO_INCREMENT,
  `nombre_departamento` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`empresas` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(100) NOT NULL,
  `direccion_empresa` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`area_dpto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`area_dpto` (
  `id_area_dpto` INT NOT NULL AUTO_INCREMENT,
  `id_departamento` INT NULL DEFAULT NULL,
  `id_empresa` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_area_dpto`),
  INDEX `id_departamento` (`id_departamento` ASC) VISIBLE,
  INDEX `id_empresa` (`id_empresa` ASC) VISIBLE,
  CONSTRAINT `area_dpto_ibfk_1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `helpdesk`.`departamentos` (`id_departamento`),
  CONSTRAINT `area_dpto_ibfk_2`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `helpdesk`.`empresas` (`id_empresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `descripcion_rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `n_identificacion` VARCHAR(10) NOT NULL,
  `nombres_usuario` VARCHAR(100) NOT NULL,
  `apellidos_usuario` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `correo_electronico` VARCHAR(200) NOT NULL,
  `clave` VARCHAR(10) NOT NULL,
  `id_rol` INT NOT NULL,
  `codigo_anydesk` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `id_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `helpdesk`.`roles` (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `helpdesk`.`formulario_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `helpdesk`.`formulario_solicitudes` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `ticket_solicitud` VARCHAR(5) NOT NULL,
  `tipo_incosistencia` VARCHAR(20) NOT NULL,
  `descripcion_detallada` VARCHAR(500) NOT NULL,
  `descripcion_corta` VARCHAR(250) NOT NULL,
  `id_area_dpto` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `estado` VARCHAR(40) NULL DEFAULT 'Por asignar',
  `fecha_corta_registro` DATE NULL DEFAULT NULL,
  `fecha_larga_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_solicitud`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_area_dpto` (`id_area_dpto` ASC) VISIBLE,
  CONSTRAINT `formulario_solicitudes_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `helpdesk`.`usuarios` (`id_usuario`),
  CONSTRAINT `formulario_solicitudes_ibfk_2`
    FOREIGN KEY (`id_area_dpto`)
    REFERENCES `helpdesk`.`area_dpto` (`id_area_dpto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
